/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProhibitedItemsRouteImport } from './routes/prohibited-items'
import { Route as RiskDisclosureRouteImport } from './routes/risk-disclosure'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustSafetyRouteImport } from './routes/trust-safety'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProhibitedItemsRoute = ProhibitedItemsRouteImport.update({
  id: '/prohibited-items',
  path: '/prohibited-items',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclosureRoute = RiskDisclosureRouteImport.update({
  id: '/risk-disclosure',
  path: '/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustSafetyRoute = TrustSafetyRouteImport.update({
  id: '/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/privacy'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/status'
    | '/terms'
    | '/trust-safety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/privacy'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/status'
    | '/terms'
    | '/trust-safety'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/privacy'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/status'
    | '/terms'
    | '/trust-safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  ProhibitedItemsRoute: typeof ProhibitedItemsRoute
  RiskDisclosureRoute: typeof RiskDisclosureRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  TrustSafetyRoute: typeof TrustSafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohibited-items': {
      id: '/prohibited-items'
      path: '/prohibited-items'
      fullPath: '/prohibited-items'
      preLoaderRoute: typeof ProhibitedItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclosure': {
      id: '/risk-disclosure'
      path: '/risk-disclosure'
      fullPath: '/risk-disclosure'
      preLoaderRoute: typeof RiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-safety': {
      id: '/trust-safety'
      path: '/trust-safety'
      fullPath: '/trust-safety'
      preLoaderRoute: typeof TrustSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  ProhibitedItemsRoute: ProhibitedItemsRoute,
  RiskDisclosureRoute: RiskDisclosureRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  TrustSafetyRoute: TrustSafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
