/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ProhibitedItemsRouteImport } from './routes/prohibited-items'
import { Route as RiskDisclosureRouteImport } from './routes/risk-disclosure'
import { Route as TrustSafetyRouteImport } from './routes/trust-safety'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ProhibitedItemsRoute = ProhibitedItemsRouteImport.update({
  id: '/prohibited-items',
  path: '/prohibited-items',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclosureRoute = RiskDisclosureRouteImport.update({
  id: '/risk-disclosure',
  path: '/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustSafetyRoute = TrustSafetyRouteImport.update({
  id: '/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/trust-safety': typeof TrustSafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/trust-safety': typeof TrustSafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/trust-safety': typeof TrustSafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/trust-safety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/trust-safety'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/trust-safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ProhibitedItemsRoute: typeof ProhibitedItemsRoute
  RiskDisclosureRoute: typeof RiskDisclosureRoute
  TrustSafetyRoute: typeof TrustSafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohibited-items': {
      id: '/prohibited-items'
      path: '/prohibited-items'
      fullPath: '/prohibited-items'
      preLoaderRoute: typeof ProhibitedItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclosure': {
      id: '/risk-disclosure'
      path: '/risk-disclosure'
      fullPath: '/risk-disclosure'
      preLoaderRoute: typeof RiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-safety': {
      id: '/trust-safety'
      path: '/trust-safety'
      fullPath: '/trust-safety'
      preLoaderRoute: typeof TrustSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  ProhibitedItemsRoute: ProhibitedItemsRoute,
  RiskDisclosureRoute: RiskDisclosureRoute,
  TrustSafetyRoute: TrustSafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
