/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProhibitedItemsRouteImport } from './routes/prohibited-items'
import { Route as RiskDisclosureRouteImport } from './routes/risk-disclosure'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustSafetyRouteImport } from './routes/trust-safety'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ItemSlugRouteImport } from './routes/item.$slug'
import { Route as ProfileHandleRouteImport } from './routes/profile.$handle'
import { Route as AuthenticatedSellNewRouteImport } from './routes/_authenticated/sell.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProhibitedItemsRoute = ProhibitedItemsRouteImport.update({
  id: '/prohibited-items',
  path: '/prohibited-items',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclosureRoute = RiskDisclosureRouteImport.update({
  id: '/risk-disclosure',
  path: '/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustSafetyRoute = TrustSafetyRouteImport.update({
  id: '/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ItemSlugRoute = ItemSlugRouteImport.update({
  id: '/item/$slug',
  path: '/item/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellNewRoute = AuthenticatedSellNewRouteImport.update({
  id: '/sell/new',
  path: '/sell/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/item/$slug': typeof ItemSlugRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/sell/new': typeof AuthenticatedSellNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/item/$slug': typeof ItemSlugRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/sell/new': typeof AuthenticatedSellNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-items': typeof ProhibitedItemsRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/item/$slug': typeof ItemSlugRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/_authenticated/sell/new': typeof AuthenticatedSellNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/privacy'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/status'
    | '/terms'
    | '/trust-safety'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/item/$slug'
    | '/profile/$handle'
    | '/sell/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/privacy'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/status'
    | '/terms'
    | '/trust-safety'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/item/$slug'
    | '/profile/$handle'
    | '/sell/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/how-it-works'
    | '/privacy'
    | '/prohibited-items'
    | '/risk-disclosure'
    | '/status'
    | '/terms'
    | '/trust-safety'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/item/$slug'
    | '/profile/$handle'
    | '/_authenticated/sell/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  ProhibitedItemsRoute: typeof ProhibitedItemsRoute
  RiskDisclosureRoute: typeof RiskDisclosureRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  TrustSafetyRoute: typeof TrustSafetyRoute
  ItemSlugRoute: typeof ItemSlugRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohibited-items': {
      id: '/prohibited-items'
      path: '/prohibited-items'
      fullPath: '/prohibited-items'
      preLoaderRoute: typeof ProhibitedItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclosure': {
      id: '/risk-disclosure'
      path: '/risk-disclosure'
      fullPath: '/risk-disclosure'
      preLoaderRoute: typeof RiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-safety': {
      id: '/trust-safety'
      path: '/trust-safety'
      fullPath: '/trust-safety'
      preLoaderRoute: typeof TrustSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/item/$slug': {
      id: '/item/$slug'
      path: '/item/$slug'
      fullPath: '/item/$slug'
      preLoaderRoute: typeof ItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sell/new': {
      id: '/_authenticated/sell/new'
      path: '/sell/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof AuthenticatedSellNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSellNewRoute: typeof AuthenticatedSellNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSellNewRoute: AuthenticatedSellNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  ProhibitedItemsRoute: ProhibitedItemsRoute,
  RiskDisclosureRoute: RiskDisclosureRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  TrustSafetyRoute: TrustSafetyRoute,
  ItemSlugRoute: ItemSlugRoute,
  ProfileHandleRoute: ProfileHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
